#cloud-config
autoinstall:
  version: 1
  # Оставляем интерактивность только если реально нужно что-то менять руками
  interactive-sections:
    - identity
  locale: ru_RU.UTF-8
  keyboard:
    layout: ru
  identity:
    hostname: mdm
    username: ss
    realname: ss
    # Пароль обязателен для валидации (здесь '1234')
    password: "$6$exDY1SdbMBRssotn$7pS7979S79S79S79S79S79S79S79S79S79S79S79S79S79S79S79S79S79S79S79S79S79"
  ssh:
    install-server: true
    allow-pw: true
  packages:
    - docker.io
    - docker-compose
    - git
    - python3-pip
    - python3-venv
    - curl
    - build-essential
  snaps:
    - name: code
      classic: true
  late-commands:
    # 1. Отключаем Wayland
    - curtin in-target -- sed -i 's/#WaylandEnable=false/WaylandEnable=false/' /etc/gdm3/custom.conf
    # 2. Права Docker
    - curtin in-target -- usermod -aG docker ss
    # 3. Создание папки проектов
    - curtin in-target -- mkdir -p /home/ss/projects
    - curtin in-target -- chown -R ss:ss /home/ss/projects
